version: '3'
services:
  db:
    image: postgres:13.0-alpine
    container_name: star_burger_db
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
  
  frontend:
    container_name: star_burger_frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend/bundles-src/:/frontend/bundles-src/
      - ./bundles:/frontend/bundles
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
  
  backend:
    container_name: star_burger_backend
    build:
      context: ./backend
    volumes:
      - ./backend:/star-burger
      - ./static:/star-burger/static
      - ./media:/star-burger/media
      - ./bundles:/star-burger/bundles
    env_file:
      - .env
    ports:
      - 8000:8000
    command: python -m gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application
    depends_on:
      - db
      - frontend

volumes:
  db_data:
  media:
  bundles:
    
