# Generated by Django 3.2.15 on 2024-10-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    def add_price_for_old_orders(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'OrderItem')
        for item in OrderItem.objects.select_related('product').iterator():
            item.price=item.product.price
            item.save()


    dependencies = [
        ('foodcartapp', '0039_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(add_price_for_old_orders),
    ]
