# Generated by Django 3.2.15 on 2024-10-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20241009_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('under', 'на рассмотрении'), ('todo', 'принят в работу'), ('delivery', 'передан в доставку'), ('end', 'завершен')], db_index=True, default='under', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
