# Generated by Django 3.2.15 on 2024-10-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20241009_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличностью'), ('noncash', 'электронно'), ('unspecified', 'не указано')], db_index=True, default='unspecified', max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
